-- MySQL Script generated by MySQL Workbench
-- 03/10/17 15:49:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Game` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Song` (
  `id` INT NOT NULL,
  `url_spofity` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `id` INT NOT NULL,
  `pseudo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game_song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Game_song` (
  `id_song` INT NOT NULL,
  `is_game` INT NULL,
  PRIMARY KEY (`id_song`),
  INDEX `id_game_1_idx` (`is_game` ASC),
  CONSTRAINT `id_song_1`
    FOREIGN KEY (`id_song`)
    REFERENCES `mydb`.`Song` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_game_1`
    FOREIGN KEY (`is_game`)
    REFERENCES `mydb`.`Game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Game_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Game_player` (
  `id_game` INT NOT NULL,
  `id_player` INT NULL,
  PRIMARY KEY (`id_game`),
  INDEX `id_player_1_idx` (`id_player` ASC),
  CONSTRAINT `id_game_2`
    FOREIGN KEY (`id_game`)
    REFERENCES `mydb`.`Game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_player_1`
    FOREIGN KEY (`id_player`)
    REFERENCES `mydb`.`Player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
